apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENV_MESSAGE: "ENV VALUE is in secret from Kubernetes ConfigMap!"


#data:
#  ENV_MESSAGE: "ENV VALUE is in secret from Kubernetes ConfigMap!"
# it will work here because in the configMap not needed base64 encoding value, so we can use data as well here and stringData.