apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  ENV_VALUE: "Hello I am coming from secret in Kubernetes Secret!"

#data:
#  ENV_VALUE: "Hello I am coming from secret in Kubernetes Secret!"
# it will not work because the value is not base64 encoded, so we use stringData instead of data.

