apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  #This is the base64 encoded value of "password". You can decode it using the command: `echo cGFzc3dvcmQ= | base64 --decode`
